### GET All
GET http://localhost:3001/api/notes

### GET One
GET http://localhost:3001/api/notes/sesdfdf


### POST
POST http://localhost:3001/api/notes
Content-Type: application/json; charset=utf-8

{"content": "poist"}